### ISSUE TITLE
Check the SSL Labs API for external domains

### ISSUE THREAD

**Issue by johnbillion** [tollmanz/wordpress-https-mixed-content-detector#22]
Just putting this out there as an idea.

For each external domain that gets blocked and then gets re-requested over HTTPS (see #21) and succeeds, we could then asynchronously hit the [SSL Labs API](https://github.com/ssllabs/ssllabs-scan) for that domain name to fetch its rating and show that next to each violation report.

We'd need some logic in there so that the report for each domain is cached and we only request it once (and atomically) for each domain name, to avoid placing too much load on the SSL Labs API.

**Comment by tollmanz** [comment]
I love this idea, but am not sure if it should be in _this_ plugin. I like the idea so much that I want a report on _every single HTTPS asset the site includes_. As such, I think a separate plugin is called for. I would then love to leverage that plugin to provide the grades for the external domains surfaced as violations in this plugin.

Thoughts?

**Comment by johnbillion** [comment]
I concur.

**Comment by tollmanz** [comment]
So...it'll be ready next week?

Closing this until you are done with the plugin.
